server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/fin2b/Desktop/personal/spring-cloud/lab1/configuration-service/config